### PR TITLE
add aria tags and roles

### PR DESCRIPTION
**Pull request by MathuraMG**
In terms of accessibility, this PR
* Add aria-roles to 'nav bar' and 'values' in preferences
* Add titles to lists 
* add 'region role' to the editor and iframe - it now shows up in the 'Landmarks' in voiceover
* make codemirror inputStyle contenteditable
@CleezyITP could you verify if the roles are ok?

It also adds parseInt to updating preferences via the input field. 
There was a bug where if you increased the value of say, fontSize after editing it in the input field - it added '2' as a string.
For instance, if I entered 12 in the input field and the pressed the increase button - the font became 122.

### CODE REVIEW

**Comment by MathuraMG** [comment]
@CleezyITP Am adding your comments here -

1) I'm worried about the "title" tag being used for the preference-menu:
https://www.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/
can we also call it a section element?
2) similarly witth the side links. instead of sidebar
Can we give it a semantic tag? like 
<aside>?

**Comment by MathuraMG** [comment]
@CleezyITP 
* I did change the preference to a section tag and tried adding the section role. However, if I don't add the title element, it reads the below on focus - 
screen shot 2016-07-13 at 11 08 42 pm

* Would `<nav>` work instead of `<aside>` - since, it's being used to navigate through the files?

**Comment by CleezyITP** [comment]
Ah, shucks. I guess I didn't know how a section behaves. Your suggestion of the <nav> sounds reasonable, but I worry it might confuse because it isn't a real nav...let's give it a try and hear some feedback about what people would prefer!

**Comment by catarak** [comment]
There's already a `<nav>` on the page already, so would it be confusing to have two?

**Comment by MathuraMG** [comment]
It should be okay to have 2 `<nav>` if we label then differently I think (we would have to use `title` though). Also seems like it might prove helpful for [screenreaders](https://www.w3.org/TR/html5/sections.html#the-nav-element) and we can navigate straight to it using landmarks.

**Comment by MathuraMG** [comment]
@CleezyITP  Do the new tags look ok for testing?

**Comment by catarak** [comment]
Let when this PR is ready to be merged!

**Comment by MathuraMG** [comment]
We got a bit more of feedback right now from Chancey - will just add those too and let you know!

**Comment by MathuraMG** [comment]
@CleezyITP Included labels for all the buttons as mentioned by Chancy. 

Since the buttons don't have labels - one option was to included a `title ` for each of them but that was being overused and the other option was to create a label and style as `display:none`. However, screen readers do not read that.
So, I followed the [suggestion on WebAIM](http://webaim.org/techniques/css/invisiblecontent/#absolutepositioning) for styling them - hope this works!

**Comment by MathuraMG** [comment]
Hi @catarak , spoke to @CleezyITP - looks like we can merge this.
Would it available on the link you sent us after it's merged?

**Comment by catarak** [comment]
All looks good! FYI, there are some labels on the Sign In/Login pages that are `display: none` and not positioned absolutely off the screen, that should probably be fixed eventually.

**Comment by MathuraMG** [comment]
Sure, I'll do that!

**Pull request merged**
